#+title: AES C
#+author: Miguel Piña
#+date: [2018-05-10 jue 12:28]
#+setupfile: ~/proyectos/org-html-themes/setup/theme-bigblow.setup

Implementación del algoritmo "Advanced Encryption Standard - AES" siguiendo las
especificaciones del /Federal Information Procesing Standards 197/.

Para compilar esta versión se requiere de un compilador que soporte C11 /(ISO/IEC
9899:2011)/ que es el estándar actual del lenguaje de C. Las versiones actuales
de GCC lo soportan.

* Compilación

Para compilar el código, basta con ejecutar la instrucción make:

#+begin_src sh
make
#+end_src

Este comando genera un ejecutable llamado *aes*.

* Ejecución

Uso: $ aes [- c | -d ] [-128 | -192 | -256] LLAVE  ARCHIVO
Herramienta para cifrar usando el algoritmo AES. LLAVE y ARCHIVO son archivos.
Se espera que el formato de la llave se encuentre en hexadecimal de tamaño 128, 192 ó 256.

Las opciones disponibles de uso son las siguientes:
       -c: para cifrar el archivo.
       -d: para descifrar el archivo.


** Ejemplo de uso:
#+begin_src sh
aes -c -128 key datos.txt
#+end_src

Donde -c es la opción de compilación, -128 es la versión de cifrado,
"key" es el archivo con la llave, y "datos.txt" es el archivo
a cifrar
